### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by ugenehan** [darren/golang-on-centos5#3]
go build bootstrap/cmd/compile/internal/ssa: /usr/local/go1.4.3/pkg/tool/linux_amd64/6g: signal: killed
go tool dist: FAILED: /usr/local/go1.4.3/bin/go install -gcflags=-l -tags=math_big_pure_go compiler_bootstrap bootstrap/cmd/...: exit status 1

**Comment by darren** [comment]
what is your build environment?  
Did you use docker,  what is the host?

**Comment by ugenehan** [comment]
> what is the host?

[root@master ~]# uname -r
3.10.0-862.el7.x86_64
[root@master ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[root@master ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by darren** [comment]
I've made some changes and tested it on centos-7.5.1804, you may give it a try.

**Comment by ugenehan** [comment]
> I've made some changes and tested it on centos-7.5.1804, you may give it a try.

The same error.
my gcc is 4.8.5 20150623

**Comment by darren** [comment]
Did you assign enough memory for your docker host?  

From your original report and this https://github.com/golang/go/issues/17825 , it is more likely that OOM is thrown when calling 6g.

If you can not assign enough memory, you may consider set GOGC as https://github.com/golang/go/issues/17825#issuecomment-262154346  has mentioned.

**Comment by darren** [comment]
No response , I assume it's fixed. 
Feel free to reopen if problem persists.
